services:
  - docker

jobs:
  include:
    - stage: build-php-7x
      script: 
      - set -e
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - cd 72/
      - docker build -t ebeyond/docker-php-7.x:latest .
      - docker push ebeyond/docker-php-7.x:latest
    - stage: build-php-5x
      script: 
      - set -e
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - cd 56/
      - docker build -t ebeyond/docker-php-5.6:latest .
      - docker push ebeyond/docker-php-5.6:latest